server:
  port: 8077
spring:
  datasource:
    #url: jdbc:mysql://60.205.226.117:3306/upload?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.134.131:3306/upload?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: luojie

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html
    cache: false
    enabled: true


  redis:
    host: 60.205.226.117
    port: 6379


qiniu:
  accessKey: Tg0coh9a85Hg9p0UDr3oQ8rRCn5mHvsZUH7j34hZ
  secretKey: RYn6gIxtAPDlAb3EQEacL4az6raezaTrCnDxTn34
  bucket: test



wechat:
  mpAppId: wx2f134bc09cc0e1a7
  mpAppSecret: 618ba4e91c3eab40957180cae6ef803b


